// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PigeonBox.Infrastructure.DataContexts;

namespace PigeonBox.Infrastructure.Migrations
{
    [DbContext(typeof(PigeonBoxContext))]
    partial class PigeonBoxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasCharSet("latin1", DelegationModes.ApplyToDatabases)
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("PigeonBox.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("AlteredAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("altered_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<bool>("Removed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("removed");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_Unique_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_Unique_Username");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlteredAt = new DateTime(2022, 7, 26, 20, 12, 19, 487, DateTimeKind.Local).AddTicks(7616),
                            CreatedAt = new DateTime(2022, 7, 26, 20, 12, 19, 488, DateTimeKind.Local).AddTicks(5694),
                            Email = "admin@admin.com.br",
                            Name = "Administrador",
                            Password = "@Asd123456789",
                            Removed = false,
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
