version: '3.4'

services:
  pigeon-box-api:
    container_name: pigeon-box
    image: pigeon-box
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build: 
      context: .
      dockerfile: Dockerfile
